l_russian:

 #DIFFICULTY_SETTINGS
 
 custom_aotsm_diff_strong_pru:0 "Усилить §YПруссию§!"
 custom_aotsm_diff_strong_aus:0 "Усилить §YАвстрийскую империю§!"
 custom_aotsm_diff_strong_byz:0 "Усилить §YРомейскую империю§!"
 custom_aotsm_diff_strong_rtu:0 "Усилить §YМладотурецкое восстание§!"
 custom_aotsm_diff_strong_rka:0 "Усилить §YИсламскую революцию§!"
 custom_aotsm_diff_strong_bul:0 "Усилить §YБолгаро-Валлахское царство§!"
 custom_aotsm_diff_strong_ser:0 "Усилить §YКоролевство Сербия§!"
 custom_aotsm_diff_strong_alb:0 "Усилить §YАлбанское королевство§!"
 custom_aotsm_diff_strong_bos:0 "Усилить §YБоснийское королевство§!"
 custom_aotsm_diff_strong_sar:0 "Усилить §YКоролевство Сардиния§!"
 custom_aotsm_diff_strong_pap:0 "Усилить §YПапскую область§!"
 custom_aotsm_diff_strong_syc:0 "Усилить §YСицилийскую республику§!"
 custom_aotsm_diff_strong_rus:0 "Усилить §YРоссийское государство§!"
 custom_aotsm_diff_strong_kaz:0 "Усилить §YКазахское ханство§!"
 custom_aotsm_diff_strong_buk:0 "Усилить §YБухарское ханство§!"
 custom_aotsm_diff_strong_hiv:0 "Усилить §YХивинское ханство§!"
 custom_aotsm_diff_strong_frr:0 "Усилить §YСоциалистическую республику Францию§!"
 custom_aotsm_diff_strong_cbi:0 "Усилить §YКонфедерацию британских островов§!"
 custom_aotsm_diff_strong_prt:0 "Усилить §YКоролевство Португалия§!"
 custom_aotsm_diff_strong_cas:0 "Усилить §YРеспублику Кастилия§!"
 custom_aotsm_diff_strong_ara:0 "Усилить §YАрагон§!"
 custom_aotsm_diff_strong_gra:0 "Усилить §YГранадское королевство§!"
 custom_aotsm_diff_strong_jas:0 "Усилить §YЯпонский сегунат§!"
 custom_aotsm_diff_strong_jap:0 "Усилить §YЯпонскую Империю§!"
 custom_aotsm_diff_strong_tuk:0 "Усилить §YТорговый союз Канто§!"
 custom_aotsm_diff_strong_qin:0 "Усилить §YИмперию Цин§!"
 custom_aotsm_diff_strong_tpn:0 "Усилить §YТайпинское восстание§!"
 custom_aotsm_diff_strong_hal:0 "Усилить §YАрабское государство§!"
 custom_aotsm_diff_strong_sor:0 "Усилить §YСомалийскуй республику§!"
 custom_aotsm_diff_strong_sos:0 "Усилить §YСомалийский султанат§!"
 
 #GAME_RULES
 
 RULE_START_WORLD_WAR:0 "Начало Великой войны"
 
 RULE_OPTION_WW_DEFAULT:0 "Стандартно"
 RULE_START_WORLD_WAR_DEFAULT_DESC:0 "В зависимости от того, включен ли исторический фокус или нет, Великая война начнется стандартно из-за польского восстания, либо какого-нибудь другого события."
 RULE_OPTION_HISTORICAL_ONLY:0 "Только историческое начало"
 RULE_START_WORLD_WAR_HISTORICAL_DESC:0 "Независимо от Ваших действий Великая война начнется из-за польского восстания."
 RULE_OPTION_NOT_HISTORICAL:0 "Не историческое начало"
 RULE_START_WORLD_WAR_NOT_HISTORICAL_DESC:0 "Германия будет игнорировать польское восстание и мировая война может начаться только из-за других событий".
 
 RULE_DIVISION_LIMITE:0 "Ограничение количества дивизий"
 RULE_DIVISION_LIMITE_ALLOWED_DESC:0 "Ограничения на дивизии будут включены, поэтому придется следить за количеством дивизий под вашим управлением."
 RULE_DIVISION_LIMITE_BLOCKED_DESC:0 "Отключает ограничение на дивизии только для игрока. Количество юнитов для ИИ-игрока будет, так же, ограничено, для сохранения опитимизации игровой компании."
 
 #AI_STRATEGIES
  
 FRR_AI_BEHAVIOR:0 "Путь §YФранции§!"
 
 RUS_AI_BEHAVIOR:0 "Путь §YРоссии§!"

 BYZ_AI_BEHAVIOR:0 "Путь §YРомеи§!"
 RULE_OPTION_TRW:0 "Путь Централизации(Исторический)"
 RULE_OPTION_TRW_BYZ_AI_DESC:0 "ИИ Ромеи будет стараться всеми силами пытаться создать централизированную империю. Основой которой будут является сторонники империи и военные."
 RULE_OPTION_RSW:0 "Путь Децентрализации"
 RULE_OPTION_RSW_BYZ_AI_DESC:0 "ИИ Ромеи будет стараться всеми силами пытаться сохранить децентрализированный статус Империи. Основывая на демократических институтах империи."
 
 PRU_AI_BEHAVIOR:0 "Путь §YПруссии§!"
 RULE_OPTION_PIW:0 "Путь Империи(Исторический)"
 RULE_OPTION_PIW_PRU_AI_DESC:0 "ИИ Пруссии будет стараться всеми силами пытаться создать единую Германию, под властью Кайзера."
 
 PRT_AI_BEHAVIOR:0 "Путь §YПортугалии§!"
 PRT_HISTORICAL:0 "Исторический путь"
 PRT_HISTORICAL_AI_DESC:0 "ИИ-Игрок остается в альянсе с государством [CBI.GetName] и поддерживает дружеские отношения с союзниками."
 
 AUS_FALL_OR_NOT_BEHAVIOR:0 "Падение Австрии"
 RULE_OPTION_AUS_WILL_FALL:0 "Австрия должна пасть"
 RULE_OPTION_AUS_WILL_FALL_DESC:0 "ИИ Австрии будет специально помогать Пруссии побеждать себя раз за разом."
 RULE_OPTION_AUS_TRY_TO_NO_FALL:0 "Австрия будет стараться выжить"
 RULE_OPTION_AUS_TRY_TO_NO_FALL_DESC:0 "ИИ Австрии постарается дать максимальный отпор Пруссии и в идеале даже победить её"
