l_english:

 #DIFFICULTY_SETTINGS
 
 custom_aotsm_diff_strong_pru:0 "Strengthen §YPrussia§!"
 custom_aotsm_diff_strong_aus:0 "Strengthen §YAustrian Empire§!"
 custom_aotsm_diff_strong_byz:0 "Strengthen §YRhomean Empire§!"
 custom_aotsm_diff_strong_rtu:0 "Strengthen §YYoung Turk Revolt§!"
 custom_aotsm_diff_strong_rka:0 "Strengthen §YIslamic Revolution§!"
 custom_aotsm_diff_strong_bul:0 "Strengthen §YBulgaro-Wallachian Kingdom§!"
 custom_aotsm_diff_strong_ser:0 "Strengthen §YKingdom of Serbia§!"
 custom_aotsm_diff_strong_alb:0 "Strengthen §YKingdom of Albania§!"
 custom_aotsm_diff_strong_bos:0 "Strengthen §YKingdom of Bosnia§!"
 custom_aotsm_diff_strong_sar:0 "Strengthen §YKingdom of Sardinia§!"
 custom_aotsm_diff_strong_pap:0 "Strengthen §YPapal States§!"
 custom_aotsm_diff_strong_syc:0 "Strengthen §YSicilian Republic§!"
 custom_aotsm_diff_strong_rus:0 "Strengthen §YRussian State§!"
 custom_aotsm_diff_strong_kaz:0 "Strengthen §YKazakh Khanate§!"
 custom_aotsm_diff_strong_buk:0 "Strengthen §YBukhara Khanate§!"
 custom_aotsm_diff_strong_hiv:0 "Strengthen §YKhiva Khanate§!"
 custom_aotsm_diff_strong_frr:0 "Strengthen §YSocialist Republic of France§!"
 custom_aotsm_diff_strong_cbi:0 "Strengthen §YConfederation of British Isles§!"
 custom_aotsm_diff_strong_prt:0 "Strengthen §YKingdom of Portugal§!"
 custom_aotsm_diff_strong_cas:0 "Strengthen §YKingdom of Castile§!"
 custom_aotsm_diff_strong_ara:0 "Strengthen §YAragon§!"
 custom_aotsm_diff_strong_gra:0 "Strengthen §YKingdom of Granada§!"
 custom_aotsm_diff_strong_jas:0 "Strengthen §YJapanese Shogunate§!"
 custom_aotsm_diff_strong_jap:0 "Strengthen §YEmpire of Japan§!"
 custom_aotsm_diff_strong_tuk:0 "Strengthen §YKanto Trade Union§!"
 custom_aotsm_diff_strong_qin:0 "Strengthen §YQing Empire§!"
 custom_aotsm_diff_strong_tpn:0 "Strengthen §YTaiping Rebellion§!"
 custom_aotsm_diff_strong_hal:0 "Strengthen §YArab State§!"
 custom_aotsm_diff_strong_sor:0 "Strengthen §YSomali Republic§!"
 custom_aotsm_diff_strong_sos:0 "Strengthen §YSomali Sultanate§!"
 custom_aotsm_diff_strong_afg:0 "Strengthen §YAfghanistan§!"
 custom_aotsm_diff_strong_kir:0 "Strengthen §YCyrenaica§!"
 custom_aotsm_diff_strong_tri:0 "Strengthen §YTripolitania§!"
 
 #GAME_RULES
 
 RULE_START_WORLD_WAR:0 "Start of the Great War"

 RULE_OPTION_WW_DEFAULT:0 "Standard"
 RULE_START_WORLD_WAR_DEFAULT_DESC:0 "Depending on whether the historical focus is enabled or not, the Great War will start normally due to the Polish uprising or some other event."
 RULE_OPTION_HISTORICAL_ONLY:0 "Historical Start Only"
 RULE_START_WORLD_WAR_HISTORICAL_DESC:0 "Regardless of your actions, the Great War will start due to the Polish uprising."
 RULE_OPTION_NOT_HISTORICAL:0 "Non-Historical Start"
 RULE_START_WORLD_WAR_NOT_HISTORICAL_DESC:0 "Germany will ignore the Polish uprising and the world war can only start due to other events."

 RULE_DIVISION_LIMITE:0 "Division Limit"

 RULE_OPTION_DIVISION_LIMITE_ON:0 "Enabled"
 RULE_OPTION_DIVISION_LIMITE_ON_DESC:0 "Division limits will be enabled, so you will have to monitor the number of divisions under your control."

 RULE_OPTION_DIVISION_LIMITE_OFF:0 "Disabled"
 RULE_OPTION_DIVISION_LIMITE_OFF_DESC:0 "Disables division limits only for the player. The number of units for AI players will still be limited to maintain game optimization."

 RULE_COLOUR_OF_SUBJECTS:0 "Coloring of Subject States"

 RULE_OPTION_SUBJECT_COLOUR_ON:0 "Enable"
 RULE_OPTION_SUBJECT_COLOUR_ON_DESC:0 "A country that is a puppet will be colored the same as the state it depends on.\n\n This option was added at the request of §YTyutcheV_V§!, many thanks to him."

 RULE_OPTION_SUBJECT_COLOUR_OFF:0 "Disable"
 RULE_OPTION_SUBJECT_COLOUR_OFF_DESC:0 "Puppet states will keep the default color or the one intended by the mod authors."

 RULE_ALLOW_INTERNATIONAL_MARKET:0 "International Market"

 RULE_OPTION_IM_FREE:0 "Free Trade (Not Recommended)"
 RULE_ALLOW_INTERNATIONAL_MARKET_ONLY_IN_1_FREE_DESC:0 "Use of the international market by AI and Player is unrestricted."

 RULE_OPTION_ONLY_IN_1_FACTION:0 "Only Within One Alliance"
 RULE_ALLOW_INTERNATIONAL_MARKET_ONLY_IN_1_FACTION_DESC:0 "The international market is available with restrictions, only within one alliance."
 
 #AI_STRATEGIES
  
 FRR_AI_BEHAVIOR:0 "Path of the §YFrance§ state!"

 RULE_OPTION_AUTHORITARIAN_ALTERNATIVE:0 "Authoritarian (Alternative)"
 RULE_OPTION_AUTHORITARIAN_ALTERNATIVE_FRR_AI_DESC:0 ""

 RULE_OPTION_AUTHORITARIAN:0 "Authoritarian"
 RULE_OPTION_AUTHORITARIAN_FRR_AI_DESC:0 "The AI player will bring Henri Charles de Artois to power"

 RULE_OPTION_FRANCE_DEMOCRATIC_RULE:0 "Democracy"
 RULE_OPTION_DEMOCRATIC_FRR_AI_DESC:0 "The AI player will bring Michel Chevalier to power and lead the country on the path of democracy"

 RULE_OPTION_REACTIONIST:0 "Reactionism"
 RULE_OPTION_REACTIONIST_FRR_AI_DESC:0 "The AI player will bring Louis Napoleon to power"

 RULE_OPTION_SOCIALIST_HISTORICAL:0 "Socialism (Historical)"
 RULE_OPTION_SOCIALIST_HISTORICAL_FRR_AI_DESC:0 "Charles Lagrange will survive the assassination attempt and retain the post of head of the French government"

 RULE_OPTION_SOCIALIST_ALTERNATIVE:0 "Socialism (Alternative)"
 RULE_OPTION_SOCIALIST_ALTERNATIVE_FRR_AI_DESC:0 "The AI player will bring Louis Blanc to power"

 RUS_AI_BEHAVIOR:0 "Path of the §YRussia§ state!"

  RUS_HISTORICAL:0 "Historical"
  RUS_HISTORICAL_AI_DESC:0 "The AI player will bring Dmitry A. Milyutin to power and lead the country on the path of liberal reforms."

  RUS_MILYUTIN_DM_WAY:0 "Dmitry Milyutin in power"
  RUS_MILYUTIN_DM_WAY_AI_DESC:0 "The AI player will bring Dmitry Milyutin to power and lead the country on the path of liberal reforms."

  RUS_ROMANOV_KN_WAY:0 "Konstantin Romanov in power"
  RUS_ROMANOV_KN_WAY_AI_DESC:0 "The AI player will bring Konstantin Romanov to power and lead the country on the path of conservative policy."

  RUS_ORLOV_MF_WAY:0 "M.F. Orlov in power"
  RUS_ORLOV_MF_WAY_AI_DESC:0 "The AI player will bring M.F. Orlov to power and lead the country on the path of militarization."

  RUSSIA_CHERNYSHEVSKY_NG_WAY:0 "N.G. Chernyshevsky in power"
  RUSSIA_CHERNYSHEVSKY_NG_WAY_AI_DESC:0 "The AI player will carry out a socialist coup and bring Nikolay Gavrilovich Chernyshevsky to power."

  RUSSIA_GERTSEN_AI_WAY:0 "A.I. Herzen in power"
  RUSSIA_GERTSEN_AI_WAY_AI_DESC:0 "The AI player will carry out a socialist coup and bring Alexander Ivanovich Herzen to power."

  RUSSIA_PUSHKIN_AS_WAY:0 "A.S. Pushkin in power"
  RUSSIA_PUSHKIN_AS_WAY_AI_DESC:0 "The AI player will carry out a socialist coup and bring Alexander Sergeyevich Pushkin to power, leading to radicalization of domestic policy."

 BYZ_AI_BEHAVIOR:0 "Path of the §YRhomean Empire§!"

  RULE_OPTION_TRW:0 "Centralization Path (Historical)"
  RULE_OPTION_TRW_BYZ_AI_DESC:0 "The Rhomean AI will try with all its might to create a centralized empire, based on imperial supporters and the military."

  RULE_OPTION_RSW:0 "Decentralization Path"
  RULE_OPTION_RSW_BYZ_AI_DESC:0 "The Rhomean AI will try with all its might to maintain the decentralized status of the Empire, based on democratic institutions."

 PRU_AI_BEHAVIOR:0 "Path of the §YPrussia§ state!"

  RULE_OPTION_PIW_SOC:0 "Empire Path (Historical)"
  RULE_OPTION_PIW_SOC_PRU_AI_DESC:0 "The Prussian AI will try with all its might to create a unified Germany under the rule of the Kaiser's son."

  RULE_OPTION_PIW_AUT:0 "Empire Path (Authoritarian)"
  RULE_OPTION_PIW_PRU_AUT_AI_DESC:0 "The Prussian AI will try with all its might to create a unified Germany under the rule of the old Kaiser."

  RULE_OPTION_PBW:0 "Bismarck Path (Democracy)"
  RULE_OPTION_PBW_PRU_AI_DESC:0 "The Prussian AI will try with all its might to create a unified Germany under the rule of Otto von Bismarck."

  RULE_OPTION_PJW:0 "Junkers Path (Reactionism)"
  RULE_OPTION_PJW_PRU_AI_DESC:0 "The Prussian AI will try with all its might to create a unified Germany under the rule of the Junkers."

  PRU_BS_AI_BEHAVIOR:0 "The Coming of the §0Black Sun§! in §YPrussia§!"

  PRU_BS_NOT_COME_TO_RULE:0 "The Black Sun will not rise over Germany"
  PRU_BS_NOT_COME_TO_RULE_DESC:0 "This rule will make the AI do everything possible to prevent the Black Sun from coming to power."

  PRU_BS_COME_TO_RULE:0 "Die schwarze Sonne wird über Deutschland leuchten"
  PRU_BS_COME_TO_RULE_DESC:0 "Choosing this option will make the AI in Germany bring terrible evil to the German lands... §0Good luck, my Führer§!."
 
  RULE_PRT_AI_BEHAVIOR:0 "Path of the §YPortugal state§!"

  PRT_HISTORICAL:0 "Historical Path"
  PRT_HISTORICAL_AI_DESC:0 "The AI player remains in alliance with the §YConfederation of British Isles§! and maintains friendly relations with allies."
  PRT_REACTIONIST:0 "Military Coup"
  PRT_REACTIONIST_AI_DESC:0 "Antonio José de Ávila seizes power in the country, leading to a break in allied relations between London and Lisbon."
  PRT_DEMOCRATIC:0 "Victory of Liberalism"
  PRT_DEMOCRATIC_AI_DESC:0 "Antonio Maria de Fontes comes to power and leads the country on the path of liberalization. Allied relations with London are preserved."
  PRT_SOCIALIST:0 "Victory of the Proletariat"
  PRT_SOCIALIST_AI_DESC:0 "Antonio Dias de Oliveira comes to power. Relations with London break off and the country follows the path of the 'Iberian Revolution'."

 AUS_FALL_OR_NOT_BEHAVIOR:0 "Fall of the §YAustrian Empire§!"

  RULE_OPTION_AUS_WILL_FALL:0 "Austria Must Fall"
  RULE_OPTION_AUS_WILL_FALL_DESC:0 "The Austrian AI will deliberately help Prussia defeat itself repeatedly."

  RULE_OPTION_AUS_TRY_TO_NO_FALL:0 "Austria Will Try to Survive"
  RULE_OPTION_AUS_TRY_TO_NO_FALL_DESC:0 "The Austrian AI will try to resist Prussia as much as possible and ideally even defeat it.\n\n§RNot recommended. The Austrian victory is undeveloped and breaks further game events!§!"
